# Generated by Django 2.2 on 2020-06-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200624_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_perimeterBased_purchase',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
