# Generated by Django 2.2 on 2020-07-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_last_perimeterbased_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hotelBased_searches',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='perimeterBased_searches',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
