# Generated by Django 2.2 on 2020-06-23 09:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_analysis_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='content',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='plotdata',
        ),
        migrations.AddField(
            model_name='analysis',
            name='adults',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysis',
            name='checkin_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysis',
            name='checkout_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysis',
            name='children',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysis',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysis',
            name='rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PerimeterBased',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startpoint_lat', models.FloatField()),
                ('startpoint_lon', models.FloatField()),
                ('perimeter', models.FloatField()),
                ('stars_min', models.FloatField()),
                ('stars_max', models.FloatField()),
                ('cust_rating_min', models.FloatField()),
                ('cust_rating_max', models.FloatField()),
                ('plotdata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('analysis_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Analysis')),
            ],
        ),
        migrations.CreateModel(
            name='HotelBased',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotels', django.contrib.postgres.fields.jsonb.JSONField()),
                ('plotdata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('analysis_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Analysis')),
            ],
        ),
    ]
