# Generated by Django 2.2 on 2020-06-23 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20200623_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='checkin_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='checkout_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hotelbased',
            name='analysis_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analysis.Analysis'),
        ),
        migrations.AlterField(
            model_name='perimeterbased',
            name='analysis_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analysis.Analysis'),
        ),
    ]
