# Generated by Django 2.2 on 2020-06-23 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_auto_20200623_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbased',
            name='analysis_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Analysis'),
        ),
        migrations.AlterField(
            model_name='perimeterbased',
            name='analysis_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Analysis'),
        ),
    ]
