# Generated by Django 2.2 on 2020-06-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_auto_20200623_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='name',
            field=models.CharField(default='First', max_length=220),
            preserve_default=False,
        ),
    ]
